spring:
  application:
    name: product-service
  cloud:
    service-registry:
      auto-registration:
        enabled: true

server:
  port: 8083

eureka:
  client:
    service-url.defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    register-with-eureka: true
    enabled: true
  instance:
    prefer-ip-address: true
