spring:
  application:
    name: inventory-service

server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
      register-with-eureka: true
  instance:
    prefer-ip-address: true
